/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: activechannel
  Dimensions:  64 * 35
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsactivechannel[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palactivechannel = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsactivechannel[0]
};



const unsigned char acactivechannel[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,	
  XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXX_, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXX__, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _X__XXX_, ___XX___, _X__X__X, XX__XX__, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _X__XX__, XX__XX__, XX__X__X, XX__X__X, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _X__XX__, XXXXXX__, XX__XX__, X__XX__X, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _X__XX__, XXXXXX__, XX__XX__, X__XX___, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, _____X__, XXXXXX__, XX__XX__, X__XX__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__X__, XX__XX__, XX__XXX_, __XXX__X, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__XX_, ___XXXX_, _X__XXX_, __XXXX__, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,  
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXX___XX, X___XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX__X, XXXXXXXX,
  XXXXXXXX, XX__XX__, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX__X, XXXXXXXX,
  XXXXXXXX, X__XXXX_, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XX__X, XXXXXXXX,
  XXXXXXXX, X__XXXXX, XX____XX, XX___XXX, _____XX_, ____XX__, XX__X__X, XXXXXXXX,
  XXXXXXXX, X__XXXXX, XX__X__X, X__X__XX, X__X__XX, __X__X__, XX__X__X, XXXXXXXX,
  XXXXXXXX, X__XXXXX, XX__X__X, XXX___XX, X__X__XX, __X__X__, ____X__X, XXXXXXXX,
  XXXXXXXX, X__XXXXX, XX__X__X, XX_X__XX, X__X__XX, __X__X__, XXXXX__X, XXXXXXXX,
  XXXXXXXX, XX__XXX_, XX__X__X, X__X__XX, X__X__XX, __X__X__, XX__X__X, XXXXXXXX,
  XXXXXXXX, XXX____X, X___X___, XX_____X, X__X__XX, __X__XX_, ___XX__X, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX  

};

const GUI_BITMAP bmactivechannel = {
 64, /* XSize */
 35, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 acactivechannel,  /* Pointer to picture data (indices) */
 &Palactivechannel  /* Pointer to palette */
};

/* *** End of file *** */
