/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: address
  Dimensions:  64 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsaddress[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Paladdress = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsaddress[0]
};



const unsigned char acaddress[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXX___XX, XXXXX__X, XXXX__XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXX___XX, XXXXX__X, XXXX__XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX__X__X, XX__X__X, X__X__X_, ___XX___, _XXX____, XXX____X, XXXXXXXX,
  XXXXXXXX, XX__X__X, X__X___X, __X___X_, _XXX__XX, __X__XX_, _X__XX__, XXXXXXXX,
  XXXXXXXX, XX__X__X, X__XX__X, __XX__X_, _XXX__XX, __X___XX, XX___XXX, XXXXXXXX,
  XXXXXXXX, XX__X__X, X__XX__X, __XX__X_, _XXX____, __XX____, XXX____X, XXXXXXXX,
  XXXXXXXX, X_______, X__XX__X, __XX__X_, _XXX__XX, XXXXXX__, _XXXX___, XXXXXXXX,
  XXXXXXXX, X__XXX__, X__X___X, __X___X_, _XXX__XX, __X__XX_, _X__XX__, XXXXXXXX,
  XXXXXXXX, X__XXX__, XX__X__X, X__X__X_, _XXXX___, _XXX____, XXX____X, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmaddress = {
 64, /* XSize */
 16, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 acaddress,  /* Pointer to picture data (indices) */
 &Paladdress  /* Pointer to palette */
};

/* *** End of file *** */
