/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: battery_discharge
  Dimensions:  64 * 35
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsbattery_discharge[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palbattery_discharge = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsbattery_discharge[0]
};



const unsigned char acbattery_discharge[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XXXXXX_X, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XXXXX__X, X__XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXX__, __XX____, ____XX__, __XXX___, ___XXX__, XXXXXXXX,
  XXXXXXXX, XXXX____, __XXX_XX, X__XX__X, X__XX__X, X__XX__X, X__XXX__, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXX_, ___XX__X, X__XX__X, X__XX__X, XX__X__X, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXX__, X__XX__X, X__XX___, ___XX__X, XX__X__X, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XX__X, X__XX__X, X__XX__X, XXXXX__X, XX__X__X, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XX__X, X__XX__X, X__XX__X, X__XX__X, XXX___XX, XXXXXXXX,
  XXXXXXXX, XXXX____, __XXXX__, ___XXX__, XX__XX__, __XXX__X, XXX___XX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXX_____, XXXX__XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXX__XX_, _XXX__XX, XXXXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXX__XXX, __XXXXXX, XXXXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXX__XXX, __XX__XX, ____XXX_, ___XX__X, __XXXX__, __XXX___, _XX__X__, XXX____X,
  XXX__XXX, __XX__X_, _XX__X__, XX__X___, X__XX_XX, X__XX__X, XX__X___, XX__XX__,
  XXX__XXX, __XX__X_, __XXXX__, XXXXX__X, X__XXXX_, ___XX__X, XX__XX__, XX__XX__,
  XXX__XXX, __XX__XX, ____XX__, XXXXX__X, X__XXX__, X__XX__X, XX__XX__, XX______,
  XXX__XXX, __XX__XX, XX___X__, XXXXX__X, X__XX__X, X__XX__X, XX__XX__, XX__XXXX,
  XXX__XX_, _XXX__X_, _XX__X__, XX__X__X, X__XX__X, X__XX__X, XX__X___, XX__XX__,
  XXX_____, XXXX__XX, ____XXX_, ___XX__X, X__XXX__, ___XX__X, XXX__X__, XXX____X,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_XXX__, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX____X, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmbattery_discharge = {
 64, /* XSize */
 35, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 acbattery_discharge,  /* Pointer to picture data (indices) */
 &Palbattery_discharge  /* Pointer to palette */
};

/* *** End of file *** */
