/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: baudrate
  Dimensions:  64 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsbaudrate[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palbaudrate = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsbaudrate[0]
};



const unsigned char acbaudrate[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXX____, __XXXXXX, XXXXXXXX, XXXXXX__, XXXX____, __XXXXXX, XXXX_XXX, XXXXXXXX,
  XXXX__XX, X__XXXXX, XXXXXXXX, XXXXXX__, XXXX__XX, X__XXXXX, XXX__XXX, XXXXXXXX,
  XXXX__XX, X__XX___, _XX__XX_, _XX__X__, XXXX__XX, X__XX___, _X____XX, ____XXXX,
  XXXX__XX, X__X_XXX, __X__XX_, _X__X___, XXXX__XX, X__X_XXX, __X__XX_, _XX__XXX,
  XXXX____, __XXXX__, __X__XX_, _X__XX__, XXXX____, __XXXX__, __X__XX_, _XX__XXX,
  XXXX__XX, X__XX__X, __X__XX_, _X__XX__, XXXX__XX, __XXX__X, __X__XX_, _____XXX,
  XXXX__XX, X__X__XX, __X__XX_, _X__XX__, XXXX__XX, X__X__XX, __X__XX_, _XXXXXXX,
  XXXX__XX, X__X__XX, __X__X__, _X__X___, XXXX__XX, X__X__XX, __X__XX_, _XX__XXX,
  XXXX____, __XXX___, __XX__X_, _XX__X__, XXXX__XX, XX__X___, __XX__XX, ____XXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmbaudrate = {
 64, /* XSize */
 16, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 acbaudrate,  /* Pointer to picture data (indices) */
 &Palbaudrate  /* Pointer to palette */
};

/* *** End of file *** */
