/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: cled_s
  Dimensions:  64 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorscled_s[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palcled_s = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorscled_s[0]
};



const unsigned char accled_s[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_____XX, X__XXXXX, X______X, X_____XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXX__X, X__XXXXX, X__XXXXX, X__XX__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, X__XXXXX, X__XXXXX, X__XXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, X__XXXXX, X__XXXXX, X__XXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, X__XXXXX, X______X, X__XXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, X__XXXXX, X__XXXXX, X__XXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, X__XXXXX, X__XXXXX, X__XXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, X__XXXXX, X__XXXXX, X__XXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXX__X, X__XXXXX, X__XXXXX, X__XX__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_____XX, X______X, X______X, X_____XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmcled_s = {
 64, /* XSize */
 16, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 accled_s,  /* Pointer to picture data (indices) */
 &Palcled_s  /* Pointer to palette */
};

/* *** End of file *** */
