/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: cpcv
  Dimensions:  64 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorscpcv[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palcpcv = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorscpcv[0]
};



const unsigned char accpcv[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, X_____XX, ______XX, XXXXXXXX, XXXXXXXX, XXX_____, X__XXXXX, __XXXXXX,
  XXXXXXXX, __XXX__X, __XXX__X, XXXXXXXX, XXXXXXXX, XX__XXX_, ___XXXXX, __XXXXXX,
  XXXXXXX_, _XXXXXXX, __XXX__X, XXXXXXXX, XXXXXXXX, X__XXXXX, XX__XXX_, _XXXXXXX,
  XXXXXXX_, _XXXXXXX, __XXX__X, XXXXXXX_, _XXXXXXX, X__XXXXX, XX__XXX_, _XXXXXXX,
  XXXXXXX_, _XXXXXXX, __XXX__X, XXXXXXX_, _XXXXXXX, X__XXXXX, XX__XXX_, _XXXXXXX,
  XXXXXXX_, _XXXXXXX, ______XX, XXXXX___, ___XXXXX, X__XXXXX, XXX__X__, XXXXXXXX,
  XXXXXXX_, _XXXXXXX, __XXXXXX, XXXXXXX_, _XXXXXXX, X__XXXXX, XXX__X__, XXXXXXXX,
  XXXXXXX_, _XXXXXXX, __XXXXXX, XXXXXXX_, _XXXXXXX, X__XXXXX, XXX__X__, XXXXXXXX,
  XXXXXXXX, __XXX__X, __XXXXXX, XXXXXXXX, XXXXXXXX, XX__XXX_, _XXX___X, XXXXXXXX,
  XXXXXXXX, X_____XX, __XXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, XXXX___X, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmcpcv = {
 64, /* XSize */
 16, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 accpcv,  /* Pointer to picture data (indices) */
 &Palcpcv  /* Pointer to palette */
};

/* *** End of file *** */
