/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: cvcc
  Dimensions:  64 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorscvcc[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palcvcc = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorscvcc[0]
};



const unsigned char accvcc[] = {
  XXXXXXXX,XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX,XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX,XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX,XXXXXX__, __X__XXX, XX__XXXX, XXXXXX__, __XXXX__, __XXXXXX, XXXXXXXX,
  XXXXXXXX,XXXXX__X, X__X__XX, X__XXXXX, XXXXX__X, X__XX__X, X__XXXXX, XXXXXXXX,
  XXXXXXXX,XXXX__XX, XXXX__XX, X__XXXXX, XXXX__XX, XXXX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX,XXXX__XX, XXXX__XX, X__XXXXX, XXXX__XX, XXXX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX,XXXX__XX, XXXXX__X, __XXXXXX, XXXX__XX, XXXX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX,XXXX__XX, XXXXX__X, __XXXXXX, XXXX__XX, XXXX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX,XXXX__XX, XXXXX__X, __XXXXXX, XXXX__XX, XXXX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX,XXXXX__X, X__XXX__, _XXXXXXX, XXXXX__X, X__XX__X, X__XXXXX, XXXXXXXX,
  XXXXXXXX,XXXXXX__, __XXXX__, _XXXXXXX, XXXXXX__, __XXXX__, __XXXXXX, XXXXXXXX,
  XXXXXXXX,XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX,XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX,XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX,XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmcvcc = {
 64, /* XSize */
 16, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 accvcc,  /* Pointer to picture data (indices) */
 &Palcvcc  /* Pointer to palette */
};

/* *** End of file *** */





