/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: cxcv
  Dimensions:  65 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorscxcv[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palcxcv = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorscxcv[0]
};



const unsigned char accxcv[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX, XXXXXXX_, ____X__X, XXXX__XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XXXXXXXX, XXXXXX__, XXX____X, XXXX__XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXXXX, XXXXX__X, XXXXXX__, XXX__XXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, XXXXX__X, X__XXXX_, _XXXX__X, XXXXXX__, XXX__XXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, XXXXX__X, X__XXXX_, _XXXX__X, XXXXXX__, XXX__XXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, XXXXXX__, __XXX___, ___XX__X, XXXXXXX_, _X__XXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, XXXXXXX_, _XXXXXX_, _XXXX__X, XXXXXXX_, _X__XXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, XXXXXX__, __XXXXX_, _XXXX__X, XXXXXXX_, _X__XXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__X__X, X__XXXXX, XXXXXX__, XXX__XXX, ___XXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, ___XX__X, X__XXXXX, XXXXXXX_, ____XXXX, ___XXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______
};

const GUI_BITMAP bmcxcv = {
 65, /* XSize */
 16, /* YSize */
 9, /* BytesPerLine */
 1, /* BitsPerPixel */
 accxcv,  /* Pointer to picture data (indices) */
 &Palcxcv  /* Pointer to palette */
};

/* *** End of file *** */
