/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: default
  Dimensions:  65 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsdefault[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Paldefault = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsdefault[0]
};



const unsigned char acdefault[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXX____, _XXXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, __XXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX, X__XXX_X, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, X__XXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX, X__XX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, X__XXX__, __XX____, XX____XX, X__XX__X, X__X____, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, X__XX__X, X__XX__X, X_XXX__X, X__XX__X, X__XX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, X__XX__X, X__XX__X, XXX____X, X__XX__X, X__XX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, X__XX___, ___XX__X, XX__X__X, X__XX__X, X__XX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, X__XX__X, XXXXX__X, X__XX__X, X__XX__X, X__XX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXX__XX, __XXX__X, X__XX__X, X__XX__X, X__X___X, X__XX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXX____, _XXXXX__, __XXX__X, XX_____X, XX__X__X, X__XXX__, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______
};

const GUI_BITMAP bmdefault = {
 65, /* XSize */
 16, /* YSize */
 9, /* BytesPerLine */
 1, /* BitsPerPixel */
 acdefault,  /* Pointer to picture data (indices) */
 &Paldefault  /* Pointer to palette */
};

/* *** End of file *** */
