/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: definetrigout
  Dimensions:  64 * 35
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsdefinetrigout[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Paldefinetrigout = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsdefinetrigout[0]
};



const unsigned char acdefinetrigout[] = {	
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXX__, _X__XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XX__XXXX, XXXXX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__XX_, ___X____, XX__X__X, __XXX___, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__X__, XX__X__X, XX__X___, X__X__XX, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__X__, XX__X__X, XX__X__X, X__X__XX, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__X__, ____X__X, XX__X__X, X__X____, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__X__, XXXXX__X, XX__X__X, X__X__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XX__XX__, XX__X__X, XX__X__X, X__X__XX, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ___XXXX_, ___XX__X, XX__X__X, X__XX___, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXX___, ___X____, __XXX__X, XX____XX, XXXXX___, _XXX__XX, X__X____, __XXXXXX,
  XXXXXXX_, _XXX__XX, X__XX__X, X__XX__X, XXXX__XX, __XX__XX, X__XXX__, XXXXXXXX,
  XXXXXXX_, _XXX__XX, X__XX__X, __XXXXXX, XXX__XXX, X__X__XX, X__XXX__, XXXXXXXX,
  XXXXXXX_, _XXX__XX, X__XX__X, __XXXXXX, XXX__XXX, X__X__XX, X__XXX__, XXXXXXXX,
  XXXXXXX_, _XXX____, __XXX__X, __XX___X, XXX__XXX, X__X__XX, X__XXX__, XXXXXXXX,
  XXXXXXX_, _XXX__XX, __XXX__X, __XXX__X, XXX__XXX, X__X__XX, X__XXX__, XXXXXXXX,
  XXXXXXX_, _XXX__XX, X__XX__X, __XXX__X, XXX__XXX, X__X__XX, X__XXX__, XXXXXXXX,
  XXXXXXX_, _XXX__XX, X__XX__X, X__XX__X, XXXX__XX, __XX__XX, X__XXX__, XXXXXXXX,
  XXXXXXX_, _XXX__XX, XX__X__X, XX____XX, XXXXX___, _XXXX___, __XXXX__, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX   
};

const GUI_BITMAP bmdefinetrigout = {
 64, /* XSize */
 35, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 acdefinetrigout,  /* Pointer to picture data (indices) */
 &Paldefinetrigout  /* Pointer to palette */
};

/* *** End of file *** */
