/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: deletall
  Dimensions:  64 * 35
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsdeletall[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Paldeletall = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsdeletall[0]
};



const unsigned char acdeletall[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XX__XXXX, XXXXXXX_, _XXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__XXX, XXXXXXX_, _XXXXXXX, XXX__XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__XXX, ____XXX_, _XXX____, XX____XX, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__XX_, _XX__XX_, _XX__XX_, _XX__XX_, _XX__XXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__XX_, _XX__XX_, _XX__XX_, _XX__XX_, _XX__XXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__XX_, _____XX_, _XX_____, _XX__XX_, _____XXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__XX_, _XXXXXX_, _XX__XXX, XXX__XX_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XX__XXX_, _XX__XX_, _XX__XX_, _XX__XX_, _XX__XXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ___XXXXX, ____XXX_, _XXX____, XXXX__XX, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, XXX__X__, XXXX____, __XXXXXX, XXX__XXX, XXXXXX_X, XXXXXXXX,
  XXXXXXXX, XXXXX___, XXX__X__, XXXX__XX, X__XXXXX, XXXXXXXX, XXXXX__X, XXXXXXXX,
  XXXXXXXX, XXXX__X_, _XX__X__, XXXX__XX, X__XX___, _XX__X__, X__X____, XXXXXXXX,
  XXXXXXXX, XXXX__X_, _XX__X__, XXXX__XX, X__X__XX, __X__X__, _X__X__X, XXXXXXXX,
  XXXXXXXX, XXXX__X_, _XX__X__, XXXX__XX, X__X__XX, __X__X__, XX__X__X, XXXXXXXX,
  XXXXXXXX, XXXX__X_, _XX__X__, XXXX____, __XX__XX, __X__X__, XX__X__X, XXXXXXXX,
  XXXXXXXX, XXX_____, __X__X__, XXXX__XX, XXXX__XX, __X__X__, XX__X__X, XXXXXXXX,
  XXXXXXXX, XXX__XXX, __X__X__, XXXX__XX, XXXX__XX, __X__X__, XX__X__X, XXXXXXXX,
  XXXXXXXX, XXX__XXX, __X__X__, XXXX__XX, XXXXX___, _XX__X__, XX__XX__, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmdeletall = {
 64, /* XSize */
 35, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 acdeletall,  /* Pointer to picture data (indices) */
 &Paldeletall  /* Pointer to palette */
};

/* *** End of file *** */
