/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: dyna_64x16
  Dimensions:  65 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsdyna_64x16[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Paldyna_64x16 = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsdyna_64x16[0]
};



const unsigned char acdyna_64x16[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXX__, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, X_______,
  XXXXXX__, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, X_______,
  XXXXXX__, XXX__XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXX__, XXX__X__, XXX__X__, X__XXXX_, ___XXX__, X___X__X, XX__XXX_, ___XXXXX, X_______,
  XXXXXX__, XXX__X__, XXX__X__, _X__XX_X, XX__XX__, _X___X__, XX__XX__, XX__XXXX, X_______,
  XXXXXX__, XXX__XX_, _X__XX__, XX__XXXX, ____XX__, XX__XX__, XX__XX__, XXXXXXXX, X_______,
  XXXXXX__, XXX__XX_, _X__XX__, XX__XXX_, _X__XX__, XX__XX__, XX__XX__, XXXXXXXX, X_______,
  XXXXXX__, XXX__XX_, _X__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XXXXXXXX, X_______,
  XXXXXX__, XX__XXXX, ___XXX__, XX__XX__, XX__XX__, XX__XX__, XX__XX__, XX__XXXX, X_______,
  XXXXXX__, ___XXXXX, ___XXX__, XX__XXX_, ____XX__, XX__XX__, XX__XXX_, ___XXXXX, X_______,
  XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______
};

const GUI_BITMAP bmdyna_64x16 = {
 65, /* XSize */
 16, /* YSize */
 9, /* BytesPerLine */
 1, /* BitsPerPixel */
 acdyna_64x16,  /* Pointer to picture data (indices) */
 &Paldyna_64x16  /* Pointer to palette */
};

/* *** End of file *** */
