/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: english
  Dimensions:  64 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsenglish[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palenglish = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsenglish[0]
};



const unsigned char acenglish[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, X__X__XX, XXXXXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXXXX, X__XXXXX, XXXXXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, XXX__X__, XXX__X__, X__X__XX, ____XX__, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, XXX___X_, _X__X___, X__X__X_, _XX__X__, _X__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, __X__XX_, _X__XX__, X__X__X_, __XXXX__, XX__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, XXX__XX_, _X__XX__, X__X__XX, ____XX__, XX__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, XXX__XX_, _X__XX__, X__X__XX, XX___X__, XX__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, XXX__XX_, _X__X___, X__X__X_, _XX__X__, XX__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, __X__XX_, _XX__X__, X__X__XX, ____XX__, XX__XXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX_XXX__, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmenglish = {
 64, /* XSize */
 16, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 acenglish,  /* Pointer to picture data (indices) */
 &Palenglish  /* Pointer to palette */
};

/* *** End of file *** */
