/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: ext_v_m
  Dimensions:  64 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsext_v_m[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palext_v_m = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsext_v_m[0]
};



const unsigned char acext_v_m[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXX__, ____XXXX, XXXXXX_X, XXXXXXXX, X_XXXXX_, _XXXXXXX, XX___XXX, ___XXXXX,
  XXXXXX__, XXXXXXXX, XXXXX__X, XXXXXXXX, X__XXX__, XXXXXXXX, XX___XXX, ___XXXXX,
  XXXXXX__, XXXXX__X, X__X____, XXXXXXXX, X__XXX__, XXXXXXXX, XX____X_, ___XXXXX,
  XXXXXX__, XXXXX__X, X__XX__X, XXXXXXXX, X__XXX__, XXXXXXXX, XX____X_, ___XXXXX,
  XXXXXX__, ____XX__, __XXX__X, XXXXXXXX, XX__X__X, XXXXXXXX, XX__X_X_, X__XXXXX,
  XXXXXX__, XXXXXXX_, _XXXX__X, XXXXXXXX, XX__X__X, XXXXXXXX, XX__X_X_, X__XXXXX,
  XXXXXX__, XXXXXX__, __XXX__X, XXXXXXXX, XX__X__X, XXXXXXXX, XX__X___, X__XXXXX,
  XXXXXX__, XXXXX__X, X__XX__X, XXXXXXXX, XXX___XX, XXXXXXXX, XX__X___, X__XXXXX,
  XXXXXX__, ____X__X, X__XXX__, ________, _XX___XX, X_______, ____XX_X, X__XXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};


  
  
const GUI_BITMAP bmext_v_m = {
 64, /* XSize */
 16, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 acext_v_m,  /* Pointer to picture data (indices) */
 &Palext_v_m  /* Pointer to palette */
};

/* *** End of file *** */
