/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: factorydefault
  Dimensions:  64 * 35
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsfactorydefault[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palfactorydefault = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsfactorydefault[0]
};



const unsigned char acfactorydefault[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX______, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XXX____X, XXX____X, ____XX__, __XXX___, ___XXX__, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XX_XXX__, XX__XX__, X__XX__X, X__XX__X, X__XXX__, XXXXXXXX,
  XXXXXXXX, XX______, XXXX____, XX__XXXX, X__XX__X, X__XX__X, XX__X__X, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XXX__X__, XX__XXXX, X__XX__X, X__XX__X, XX__X__X, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XX__XX__, XX__XXXX, X__XX__X, X__XX__X, XX__X__X, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XX__XX__, XX__XX__, X__XX__X, X__XX__X, XXX___XX, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XXX_____, XXX____X, XX__XX__, __XXX__X, XXX___XX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX_____X, XXXXXXXX, XXXX___X, XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XX__XX__, XXXXXXXX, XXX__XXX, XXXXXXXX, XXXXXXX_, _XXX_XXX, XXXXXXXX,
  XXXXXXXX, XX__XXX_, _XXXXXXX, XXX__XXX, XXXXXXXX, XXXXXXX_, _XX__XXX, XXXXXXXX,
  XXXXXXXX, XX__XXX_, _XXX____, XX____XX, ____XXX_, _XX__XX_, _X____XX, XXXXXXXX,
  XXXXXXXX, XX__XXX_, _XX__XX_, _XX__XX_, XXX__XX_, _XX__XX_, _XX__XXX, XXXXXXXX,
  XXXXXXXX, XX__XXX_, _XX__XX_, _XX__XXX, X____XX_, _XX__XX_, _XX__XXX, XXXXXXXX,
  XXXXXXXX, XX__XXX_, _XX_____, _XX__XXX, __X__XX_, _XX__XX_, _XX__XXX, XXXXXXXX,
  XXXXXXXX, XX__XXX_, _XX__XXX, XXX__XX_, _XX__XX_, _XX__XX_, _XX__XXX, XXXXXXXX,
  XXXXXXXX, XX__XX__, XXX__XX_, _XX__XX_, _XX__XX_, _X___XX_, _XX__XXX, XXXXXXXX,
  XXXXXXXX, XX_____X, XXXX____, XXX__XXX, _____XXX, __X__XX_, _XXX__XX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmfactorydefault = {
 64, /* XSize */
 35, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 acfactorydefault,  /* Pointer to picture data (indices) */
 &Palfactorydefault  /* Pointer to palette */
};

/* *** End of file *** */
