/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: fast_seq
  Dimensions:  65 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsfast_seq[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palfast_seq = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsfast_seq[0]
};



const unsigned char acfast_seq[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXX_, _____XXX, XXXX____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, XXX__XXX, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, XXX__XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, XXX___XX, XXXXX___, _XXXX__X, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXX____, XXXX__XX, __XX__X_, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXX_, _____XXX, XXXXX___, _XXX__XX, __XX__XX, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXX_, __XX____, __XX__XX, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, __XX__XX, XXXX__XX, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXX_, _XXXXXX_, _XX__XXX, __XX__XX, __XX__X_, __XX__XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXX_, _XXXXXX_, _XXX____, _XXXX___, _XXXX__X, __XX__XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, X_______
};

const GUI_BITMAP bmfast_seq = {
 65, /* XSize */
 16, /* YSize */
 9, /* BytesPerLine */
 1, /* BitsPerPixel */
 acfast_seq,  /* Pointer to picture data (indices) */
 &Palfast_seq  /* Pointer to palette */
};

/* *** End of file *** */
