/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: h140a
  Dimensions:  64 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsh140a[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palh140a = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsh140a[0]
};



const unsigned char ach140a[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XXX__XXX, XX__XXX_, ___XXXXX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XX___XXX, XX__XX__, XX__XXXX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, X____XXX, X___XX__, XX__XXX_, _X__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, X_X__XXX, X___XX__, XX__XXX_, _X__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ___XXXXX, XXX__XXX, _X__XX__, XX__XXX_, _X__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XXX__XXX, _X__XX__, XX__XX__, XXX__XXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XXX__XX_, XX__XX__, XX__XX__, XXX__XXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XXX__XX_, _____X__, XX__XX__, _____XXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XXX__XXX, XX__XX__, XX__X__X, XXXX__XX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XXX__XXX, XX__XXX_, ___XX__X, XXXX__XX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmh140a = {
 64, /* XSize */
 16, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 ach140a,  /* Pointer to picture data (indices) */
 &Palh140a  /* Pointer to palette */
};

/* *** End of file *** */
