/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: h1450a
  Dimensions:  64 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsh1450a[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palh1450a = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsh1450a[0]
};



const unsigned char ach1450a[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, __XXX__X, XXXXXXX_, _XXXXX__, XX______, XX____XX, XXX___XX, XXXXXXXX,
  XXXXXXXX, __XXX__X, XXXXXX__, _XXXXX__, XXXXXX__, X__XX__X, XXX___XX, XXXXXXXX,
  XXXXXXXX, __XXX__X, XXXXX___, _XXXX___, XXXXX__X, X__XX__X, XX__X__X, XXXXXXXX,
  XXXXXXXX, __XXX__X, XXXXX_X_, _XXXX___, XXXXX__X, X__XX__X, XX__X__X, XXXXXXXX,
  XXXXXXXX, _______X, XXXXXXX_, _XXX_X__, XXXX__XX, X__XX__X, XX__X__X, XXXXXXXX,
  XXXXXXXX, __XXX__X, XXXXXXX_, _XXX_X__, XXXX__XX, X__XX__X, X__XXX__, XXXXXXXX,
  XXXXXXXX, __XXX__X, XXXXXXX_, _XX_XX__, XXXX__XX, X__XX__X, X__XXX__, XXXXXXXX,
  XXXXXXXX, __XXX__X, XXXXXXX_, _XX_____, _XX__XXX, X__XX__X, X_______, XXXXXXXX,
  XXXXXXXX, __XXX__X, XXXXXXX_, _XXXXX__, XXX__XXX, X__XX__X, __XXXXX_, _XXXXXXX,
  XXXXXXXX, __XXX__X, XXXXXXX_, _XXXXX__, XXX__XXX, XX____XX, __XXXXX_, _XXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmh1450a = {
 64, /* XSize */
 16, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 ach1450a,  /* Pointer to picture data (indices) */
 &Palh1450a  /* Pointer to palette */
};

/* *** End of file *** */
