/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: h150v
  Dimensions:  65 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsh150v[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palh150v = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsh150v[0]
};



const unsigned char ach150v[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XXXX__XX, X_____XX, ____XX__, XXXXX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XXX___XX, X__XXXX_, _XX__X__, XXXXX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XX____XX, __XXXXX_, _XX__XX_, _XXX__XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XX_X__XX, _____XX_, _XX__XX_, _XXX__XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX___, ____XXXX, XXXX__XX, __XX__X_, _XX__XX_, _XXX__XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XXXX__XX, XXXX__X_, _XX__XXX, __X__XXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XXXX__XX, XXXX__X_, _XX__XXX, __X__XXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XXXX__XX, XXXX__X_, _XX__XXX, __X__XXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XXXX__XX, __XX__X_, _XX__XXX, X___XXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XXXX__XX, X____XXX, ____XXXX, X___XXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______
};

const GUI_BITMAP bmh150v = {
 65, /* XSize */
 16, /* YSize */
 9, /* BytesPerLine */
 1, /* BitsPerPixel */
 ach150v,  /* Pointer to picture data (indices) */
 &Palh150v  /* Pointer to palette */
};

/* *** End of file *** */
