/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: h15a
  Dimensions:  65 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsh15a[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palh15a = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsh15a[0]
};



const unsigned char ach15a[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXX__X, XX_____X, XXXX___X, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXX___X, XX__XXXX, XXXX___X, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXX____X, X__XXXXX, XXX__X__, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXX_X__X, X_____XX, XXX__X__, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, _______X, XXXXX__X, X__XX__X, XXX__X__, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXX__X, XXXXX__X, XX__XXX_, _XXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXX__X, XXXXX__X, XX__XXX_, _XXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXX__X, XXXXX__X, XX______, _XXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXX__X, X__XX__X, X__XXXXX, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXX__X, XX____XX, X__XXXXX, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______
};

const GUI_BITMAP bmh15a = {
 65, /* XSize */
 16, /* YSize */
 9, /* BytesPerLine */
 1, /* BitsPerPixel */
 ach15a,  /* Pointer to picture data (indices) */
 &Palh15a  /* Pointer to palette */
};

/* *** End of file *** */
