/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: h210a
  Dimensions:  65 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsh210a[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palh210a = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsh210a[0]
};



const unsigned char ach210a[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XX____XX, XXX__XXX, ____XXXX, X___XXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, X__XX__X, XX___XX_, _XX__XXX, X___XXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XXXXX__X, X____XX_, _XX__XXX, __X__XXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XXXXX__X, X_X__XX_, _XX__XXX, __X__XXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX___, ____XXXX, XXXX__XX, XXX__XX_, _XX__XXX, __X__XXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XXX___XX, XXX__XX_, _XX__XX_, _XXX__XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XXX__XXX, XXX__XX_, _XX__XX_, _XXX__XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, XX__XXXX, XXX__XX_, _XX__XX_, ______XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, X__XXXXX, XXX__XX_, _XX__X__, XXXXX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXXX__X, XX__XXXX, X______X, XXX__XXX, ____XX__, XXXXX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______
};

const GUI_BITMAP bmh210a = {
 65, /* XSize */
 16, /* YSize */
 9, /* BytesPerLine */
 1, /* BitsPerPixel */
 ach210a,  /* Pointer to picture data (indices) */
 &Palh210a  /* Pointer to palette */
};

/* *** End of file *** */
