/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: h280a
  Dimensions:  64 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsh280a[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palh280a = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsh280a[0]
};



const unsigned char ach280a[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, X____XXX, ____XXX_, ___XXXXX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, __XX__X_, _XX__X__, XX__XXXX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XXXX__X_, _XX__X__, XX__XXX_, _X__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XXXX__X_, _XX__X__, XX__XXX_, _X__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ___XXXXX, XXX__XXX, ____XX__, XX__XXX_, _X__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XX___XX_, _XX__X__, XX__XX__, XXX__XXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, XX__XXX_, _XX__X__, XX__XX__, XXX__XXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, X__XXXX_, _XX__X__, XX__XX__, _____XXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, __XXXXX_, _XX__X__, XX__X__X, XXXX__XX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, ______XX, ____XXX_, ___XX__X, XXXX__XX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmh280a = {
 64, /* XSize */
 16, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 ach280a,  /* Pointer to picture data (indices) */
 &Palh280a  /* Pointer to palette */
};

/* *** End of file *** */
