/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: h35a
  Dimensions:  65 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsh35a[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palh35a = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsh35a[0]
};



const unsigned char ach35a[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXX___, _XXX____, _XXXX___, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXX__XX, __XX__XX, XXXXX___, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXXXXX, __X__XXX, XXXX__X_, _XXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXXXXX, __X_____, XXXX__X_, _XXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, _______X, XXXXXX__, _XX__XX_, _XXX__X_, _XXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXXXXX, __XXXXX_, _XX__XXX, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXXXXX, __XXXXX_, _XX__XXX, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXXXXX, __XXXXX_, _XX_____, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXX__XX, __X__XX_, _X__XXXX, X__XXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXX___, _XXX____, XX__XXXX, X__XXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______
};

const GUI_BITMAP bmh35a = {
 65, /* XSize */
 16, /* YSize */
 9, /* BytesPerLine */
 1, /* BitsPerPixel */
 ach35a,  /* Pointer to picture data (indices) */
 &Palh35a  /* Pointer to palette */
};

/* *** End of file *** */
