/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: h500v
  Dimensions:  65 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsh500v[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palh500v = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsh500v[0]
};



const unsigned char ach500v[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, XXX__XXX, XX_____X, X____XXX, ____XXX_, _XXXXX__, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, XXX__XXX, XX__XXXX, __XX__X_, _XX__XX_, _XXXXX__, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, XXX__XXX, X__XXXXX, __XX__X_, _XX__XXX, __XXX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, XXX__XXX, X_____XX, __XX__X_, _XX__XXX, __XXX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, _____XXX, X__XX__X, __XX__X_, _XX__XXX, __XXX__X, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, XXX__XXX, XXXXX__X, __XX__X_, _XX__XXX, X__X__XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, XXX__XXX, XXXXX__X, __XX__X_, _XX__XXX, X__X__XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, XXX__XXX, XXXXX__X, __XX__X_, _XX__XXX, X__X__XX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, XXX__XXX, X__XX__X, __XX__X_, _XX__XXX, XX___XXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXX__, XXX__XXX, XX____XX, X____XXX, ____XXXX, XX___XXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______
};

const GUI_BITMAP bmh500v = {
 65, /* XSize */
 16, /* YSize */
 9, /* BytesPerLine */
 1, /* BitsPerPixel */
 ach500v,  /* Pointer to picture data (indices) */
 &Palh500v  /* Pointer to palette */
};

/* *** End of file *** */
