/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: h60a
  Dimensions:  65 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsh60a[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palh60a = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsh60a[0]
};



const unsigned char ach60a[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXXX___, XXXX____, XXXXX___, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXX_XX_, _XX__XX_, _XXXX___, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXX__XXX, XXX__XX_, _XXX__X_, _XXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXX__XXX, XXX__XX_, _XXX__X_, _XXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, _______X, XXX_____, XXX__XX_, _XXX__X_, _XXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXX__XX_, _XX__XX_, _XX__XXX, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXX__XX_, _XX__XX_, _XX__XXX, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXX__XX_, _XX__XX_, _XX_____, __XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXX__XX_, _XX__XX_, _X__XXXX, X__XXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, __XXX__X, XXXX____, XXXX____, XX__XXXX, X__XXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______
};

const GUI_BITMAP bmh60a = {
 65, /* XSize */
 16, /* YSize */
 9, /* BytesPerLine */
 1, /* BitsPerPixel */
 ach60a,  /* Pointer to picture data (indices) */
 &Palh60a  /* Pointer to palette */
};

/* *** End of file *** */
