/*
  C-file generated by emWin Bitmap converter 2.14a, compiled Mar 20 2001, 10:24:07

(c) 1998 SEGGER Microcontroller Systeme GmbH
         Tel.  49-2103-895899
         Fax.  49-2103-895860
         EMail info@segger.com
               www.segger.com




  Source file: h840a
  Dimensions:  64 * 16
  NumColors:   2
*/

#include "stdlib.h"

#include "GUI.H"

/*   Palette  


The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/
const GUI_COLOR Colorsh840a[] = {
     0x000000,0xFFFFFF
};


const GUI_LOGPALETTE Palh840a = {
  2,	/* number of entries */
  1, 	/* Has transparency */
  &Colorsh840a[0]
};



const unsigned char ach840a[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, X____XXX, XX__XXX_, ___XXXXX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, __XX__XX, XX__XX__, XX__XXXX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, __XX__XX, X___XX__, XX__XXX_, _X__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, __XX__XX, X___XX__, XX__XXX_, _X__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ___XXXXX, X____XXX, _X__XX__, XX__XXX_, _X__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, __XX__XX, _X__XX__, XX__XX__, XXX__XXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, __XX__X_, XX__XX__, XX__XX__, XXX__XXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, __XX__X_, _____X__, XX__XX__, _____XXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, __XX__XX, XX__XX__, XX__X__X, XXXX__XX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, X__XXXXX, X____XXX, XX__XXX_, ___XX__X, XXXX__XX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

const GUI_BITMAP bmh840a = {
 64, /* XSize */
 16, /* YSize */
 8, /* BytesPerLine */
 1, /* BitsPerPixel */
 ach840a,  /* Pointer to picture data (indices) */
 &Palh840a  /* Pointer to palette */
};

/* *** End of file *** */
